version: '3.7'

services:
  u-documentation-api:
    container_name: 'u-documentation-api'
    build: .
    ports:
      - ${SERVICE_PORT}:${SERVICE_PORT}
    expose:
      - ${SERVICE_PORT}
    environment:
      - SERVICE_PORT=${SERVICE_PORT}
      - GIT_KEY=${GIT_KEY}
